# Generated by Django 4.2.5 on 2023-12-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_devicedata_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicedata",
            name="latitude",
            field=models.FloatField(null=True),
        ),
    ]
