# Generated by Django 4.2.5 on 2023-12-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_devicedata_latitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicedata",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
