# Generated by Django 4.2.5 on 2023-12-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_devicedata_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicedata",
            name="timestamp",
            field=models.BigIntegerField(null=True),
        ),
    ]
