# Generated by Django 4.2.5 on 2023-12-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_devicedata_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicedata",
            name="value",
            field=models.IntegerField(null=True),
        ),
    ]
