# Generated by Django 4.2.5 on 2023-12-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_devicedata_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devicedata",
            old_name="client_id",
            new_name="clientId",
        ),
        migrations.RenameField(
            model_name="devicedata",
            old_name="latitude",
            new_name="lat",
        ),
        migrations.RenameField(
            model_name="devicedata",
            old_name="longitude",
            new_name="lng",
        ),
    ]
