# Generated by Django 4.2.5 on 2023-12-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_rename_client_id_devicedata_clientid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicedata",
            name="clientId",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
