# Generated by Django 4.2.5 on 2023-12-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_devicedata_clientid"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicedata",
            name="clientName",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="devicedata",
            name="clientType",
            field=models.TextField(null=True),
        ),
    ]
